### ISSUE TITLE
Hi my dancing gophers do not look like gophers

### ISSUE THREAD

**Issue by billiebongo** [80at8/gopherdance#3]
Am I doing smth wrong? ran the go file and i see this
<img width="860" alt="Screenshot 2020-05-31 at 4 04 09 PM" src="https://user-images.githubusercontent.com/39232407/83347626-a17d1480-a358-11ea-80ab-4803f9c00979.png">
on macOS terminal

**Comment by t1nfoil** [comment]
i built it on Ubuntu Linux with the default terminal (full screen).. what OS/Terminal are you using?

________________________________

**Comment by billiebongo** [comment]
MacOS Terminal

**Comment by t1nfoil** [comment]
ahh weird.. i could only suggest that you check to make sure your terminal can support unicode block characters and ansi escape codes.. otherwise try different terminals like xterm?

________________________________

**Comment by t1nfoil** [comment]
oh and try vt100 mode

________________________________

**Comment by andrewostroumov** [comment]
> Am I doing smth wrong? ran the go file and i see this
> <img alt="Screenshot 2020-05-31 at 4 04 09 PM" width="860" src="https://user-images.githubusercontent.com/39232407/83347626-a17d1480-a358-11ea-80ab-4803f9c00979.png">
> on macOS terminal

I have MacOS as well and really want to see dancing gophers every morning
